[package]
name = "petridish"
version = "0.2.1"
edition = "2021"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]
categories = ["command-line-utilities", "template-engine"]
description = "A command-line utility that creates project layout."
repository = "https://github.com/petridish-dev/petridish"
license = "MIT"

[dependencies]
miette = { version = "3.2.0", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1.0"
tera = "1.15"
regex = "1.5.4"
clap = "2"
structopt = { version = "0.3", features = ["suggestions", "color"] }
dialoguer = "0.9"
tempdir = "0.3"
walkdir = "2"
md5 = "0.7"
