[package]
name = "petridish"
version = "0.1.0"
edition = "2021"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]
categories = ["command-line-utilities", "template-engine"]
description = "A command-line utility that creates project layout."
repository = "https://github.com/petridish-dev/petridish"
license = "MIT"

[dependencies]
